test

diff --git a/.github/workflows/image.yaml b/.github/workflows/image.yaml
--- a/.github/workflows/image.yaml
+++ b/.github/workflows/image.yaml
@@ -27,8 +27,14 @@ jobs:
       - name: create ecr repo
         shell: bash
         run: |
-          aws ecr create-repository --repository-name movie-bot-backend --region us-east-1
-          aws ecr create-repository --repository-name movie-bot-frontend --region us-east-1
+          repo=$(aws ecr describe-repositories --repository-names movie-bot-backend || echo "not found")
+          if [ -z "$repo" ]; then
+            aws ecr create-repository --repository-name movie-bot-backend --region us-east-1
+          fi
+          repo=$(aws ecr describe-repositories --repository-names movie-bot-frontend || echo "not found")
+          if [ -z "$repo" ]; then
+            aws ecr create-repository --repository-name movie-bot-frontend --region us-east-1
+          fi
 
       - name: Authenticate docker to ecr
         shell: bash
